  sql:
    init:
      mode: always
      platform: MYSQL
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/hibernate_db?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true